/** North Eastern Lawn visual system: Cut & Collect. */
import { canCreateQuoteRequest, canCreateServiceRequest, formatCurrencyFromCents } from "@/lib/portalData";
import { Invoice, Property, ServiceVisit, supabase } from "@/lib/supabase";
import { ArrowUpRight, CalendarDays, Check, CircleDollarSign, Home, Loader2, LogOut, MapPin, Plus, Sparkles, Sprout } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

type PortalMode = "loading" | "signed-out" | "ready";
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat("en-US", { month: "short", day: "numeric", year: "numeric" }).format(new Date(value)) : "To be scheduled";

export default function CustomerDashboard() {
  const [, setLocation] = useLocation();
  const [mode, setMode] = useState<PortalMode>("loading");
  const [firstName, setFirstName] = useState("there");
  const [properties, setProperties] = useState<Property[]>([]);
  const [visits, setVisits] = useState<ServiceVisit[]>([]);
  const [invoices, setInvoices] = useState<Invoice[]>([]);
  const [quoteStatus, setQuoteStatus] = useState<string | null>(null);
  const [showQuoteForm, setShowQuoteForm] = useState(false);
  const [showPropertyForm, setShowPropertyForm] = useState(false);
  const [showRequestForm, setShowRequestForm] = useState(false);
  const [notice, setNotice] = useState("");
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  const nextVisit = useMemo(() => visits.find(visit => ["scheduled", "weather_hold"].includes(visit.status)) ?? null, [visits]);
  const outstanding = useMemo(() => invoices.filter(invoice => ["open", "overdue"].includes(invoice.status)), [invoices]);
  const isFirstTime = !properties.length && !visits.length && !invoices.length;

  async function loadPortal() {
    const { data: auth } = await supabase.auth.getSession();
    const user = auth.session?.user;
    if (!user) { setMode("signed-out"); return; }
    setFirstName((user.user_metadata.full_name || user.email || "there").split(" ")[0]);
    await supabase.from("profiles").upsert({ id: user.id, full_name: user.user_metadata.full_name || null }, { onConflict: "id" });
    const [propertyResult, visitResult, invoiceResult, quoteResult] = await Promise.all([
      supabase.from("properties").select("id,nickname,address_line1,city,state,postal_code").order("created_at"),
      supabase.from("service_visits").select("id,scheduled_start,service_type,status,notes_for_customer").order("scheduled_start").limit(8),
      supabase.from("invoices").select("id,invoice_number,amount_cents,due_date,status").order("due_date").limit(8),
      supabase.from("quote_requests").select("status").order("created_at", { ascending: false }).limit(1),
    ]);
    setProperties((propertyResult.data ?? []) as Property[]); setVisits((visitResult.data ?? []) as ServiceVisit[]); setInvoices((invoiceResult.data ?? []) as Invoice[]); setQuoteStatus(quoteResult.data?.[0]?.status ?? null);
    setError(propertyResult.error?.message || visitResult.error?.message || invoiceResult.error?.message || quoteResult.error?.message || ""); setMode("ready");
  }
  useEffect(() => { void loadPortal(); const { data } = supabase.auth.onAuthStateChange(() => void loadPortal()); return () => data.subscription.unsubscribe(); }, []);
  async function signOut() { await supabase.auth.signOut(); setLocation("/"); }
  async function addProperty(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const userId = (await supabase.auth.getSession()).data.session?.user.id; if (!userId) return setLocation("/login"); const { error: insertError } = await supabase.from("properties").insert({ profile_id: userId, nickname: String(form.get("nickname") || "My property"), address_line1: String(form.get("address")), city: String(form.get("city")), state: String(form.get("state")), postal_code: String(form.get("postalCode")) }); setBusy(false); if (insertError) return setError(insertError.message); setShowPropertyForm(false); setNotice("Property details saved."); await loadPortal(); }
  async function requestService(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const userId = (await supabase.auth.getSession()).data.session?.user.id; const input = { propertyId: String(form.get("propertyId") || ""), serviceType: String(form.get("serviceType") || ""), preferredDate: String(form.get("preferredDate") || "") }; if (!userId || !canCreateServiceRequest(input)) { setBusy(false); return setError("Choose a property, service, and preferred date."); } const { error: insertError } = await supabase.from("service_requests").insert({ profile_id: userId, property_id: input.propertyId, service_type: input.serviceType, preferred_date: input.preferredDate, notes: String(form.get("notes") || "") || null }); setBusy(false); if (insertError) return setError(insertError.message); setShowRequestForm(false); setNotice("Request received. Our team will confirm the next step."); }
  async function requestQuote(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const userId = (await supabase.auth.getSession()).data.session?.user.id; const input = { address: String(form.get("address") || ""), city: String(form.get("city") || ""), state: String(form.get("state") || ""), postalCode: String(form.get("postalCode") || ""), serviceInterests: form.getAll("services").map(value => String(value)) }; if (!userId || !canCreateQuoteRequest(input)) { setBusy(false); return setError("Add the address and choose at least one service."); } const { error: insertError } = await supabase.from("quote_requests").insert({ profile_id: userId, property_address: input.address, city: input.city, state: input.state, postal_code: input.postalCode, service_interests: input.serviceInterests, property_notes: String(form.get("notes") || "") || null }); setBusy(false); if (insertError) return setError(insertError.message); setShowQuoteForm(false); setQuoteStatus("submitted"); setNotice("Quote brief received. We’ll be in touch with the next step."); }

  if (mode === "loading") return <div className="grid min-h-screen place-items-center bg-[#f6f1e8]"><Loader2 className="h-8 w-8 animate-spin text-[#123c29]" /></div>;
  if (mode === "signed-out") return <main className="min-h-screen bg-[#123c29] p-4 text-white sm:p-8"><section className="relative mx-auto flex min-h-[calc(100vh-2rem)] max-w-6xl items-end overflow-hidden rounded-[2rem] p-7 sm:min-h-[calc(100vh-4rem)] sm:p-12"><img src="/manus-storage/north-eastern-portal_97320165.jpg" alt="Maintained North Eastern Lawn property" className="absolute inset-0 h-full w-full object-cover opacity-50" /><div className="absolute inset-0 bg-gradient-to-r from-[#123c29] via-[#123c29]/85 to-[#123c29]/25" /><div className="relative z-10 max-w-xl"><span className="grid h-12 w-12 place-items-center rounded-full bg-[#f6f1e8]"><img src="/manus-storage/north-eastern-mark_65290f75.png" alt="North Eastern Lawn" className="h-10 w-10" /></span><p className="eyebrow mt-12 text-[#dd784d]">CUSTOMER PORTAL / START HERE</p><h1 className="display mt-4 text-5xl leading-[.88] sm:text-7xl">Your quote<br /><em>starts outside.</em></h1><p className="mt-6 max-w-md text-lg leading-8 text-[#d3dfd2]">Sign in, share a few details about the place, and we’ll bring back the plan.</p><button onClick={() => setLocation("/login")} className="mt-9 inline-flex min-h-14 items-center gap-3 rounded-full bg-[#dd784d] px-6 text-sm font-black text-[#123c29]">Continue to sign-in <ArrowUpRight className="h-5 w-5" /></button><button onClick={() => setLocation("/")} className="ml-5 text-sm font-bold underline underline-offset-4">Return to website</button></div></section></main>;

  const quotePanel = <section className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><div className="relative min-h-[430px] overflow-hidden rounded-[1.7rem] bg-[#dd784d] p-7 sm:p-10"><img src="/manus-storage/north-eastern-portal_97320165.jpg" alt="Home ready for a quote" className="absolute inset-y-0 right-0 h-full w-[58%] object-cover" /><div className="absolute inset-y-0 right-[42%] w-40 bg-gradient-to-r from-[#dd784d] to-transparent" /><div className="relative z-10 max-w-sm"><Sparkles className="h-7 w-7" /><p className="eyebrow mt-14 text-[#123c29]">{quoteStatus ? "QUOTE BRIEF RECEIVED" : "START HERE"}</p><h2 className="display mt-4 text-5xl leading-[.88]">{quoteStatus ? <>We’re on<br /><em>your place.</em></> : <>Your place.<br /><em>Your quote.</em></>}</h2><p className="mt-5 max-w-[220px] text-sm font-semibold leading-6 text-[#123c29]/75">{quoteStatus ? "Your brief is with the team. We’ll come back with the best next step." : "Tell us what needs attention. Our team will shape the next step around your property."}</p>{quoteStatus ? <div className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#dff0b8] px-5 py-3 text-sm font-extrabold"><Check className="h-4 w-4" />Submitted</div> : <button onClick={() => setShowQuoteForm(true)} className="mt-7 inline-flex items-center gap-2 rounded-full bg-[#123c29] px-5 py-3 text-sm font-extrabold text-white">Build my quote <ArrowUpRight className="h-4 w-4" /></button>}</div></div><div className="grid gap-4"><div className="rounded-[1.5rem] bg-[#e7ece2] p-6"><p className="text-4xl font-black text-[#dd784d]">01</p><p className="mt-10 font-extrabold">Where is it?</p><p className="mt-2 text-sm leading-6 text-[#5c705f]">Add the address and a few property details.</p></div><div className="rounded-[1.5rem] bg-[#123c29] p-6 text-white"><p className="text-4xl font-black text-[#dd784d]">02</p><p className="mt-10 font-extrabold">What needs work?</p><p className="mt-2 text-sm leading-6 text-[#d3dfd2]">Choose the services that matter right now.</p></div><div className="rounded-[1.5rem] bg-[#dff0b8] p-6"><p className="text-4xl font-black text-[#4b743c]">03</p><p className="mt-10 font-extrabold">We’ll come back with a plan.</p></div></div></section>;
  const activePanel = <><section className="grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="paper-card p-6 sm:p-8"><div className="flex items-start justify-between"><div><p className="eyebrow">UP NEXT</p><h2 className="display mt-3 text-3xl">{nextVisit?.service_type || "Your next visit"}</h2></div><CalendarDays className="h-6 w-6 text-[#4b743c]" /></div><p className="mt-7 text-sm leading-6 text-[#5c705f]">{nextVisit ? `${formatDate(nextVisit.scheduled_start)} · ${nextVisit.notes_for_customer || "Details will appear before your visit."}` : "Nothing on the calendar yet. Send a service request when something changes."}</p></div><button onClick={() => setShowRequestForm(true)} className="rounded-[1.5rem] bg-[#dd784d] p-6 text-left"><p className="eyebrow">ACCOUNT ACTION</p><h2 className="display mt-10 text-3xl">Need a change?</h2><p className="mt-4 text-sm font-bold underline underline-offset-4">Send a service request</p></button></section><section className="grid gap-5 lg:grid-cols-2"><div className="paper-card p-6"><div className="flex justify-between"><div><p className="eyebrow">YOUR PROPERTIES</p><h2 className="display mt-3 text-3xl">On record.</h2></div><button onClick={() => setShowPropertyForm(true)} className="icon-button"><Plus className="h-5 w-5" /></button></div><div className="mt-6 space-y-4">{properties.map(property => <div key={property.id} className="flex gap-3 border-t border-[#dde2d9] pt-4"><MapPin className="h-4 w-4 text-[#4b743c]" /><p className="text-sm font-semibold">{property.nickname || property.address_line1}<br /><span className="font-normal text-[#5c705f]">{property.city}, {property.state} {property.postal_code}</span></p></div>)}</div></div><div className="paper-card p-6"><div className="flex justify-between"><div><p className="eyebrow">BILLING</p><h2 className="display mt-3 text-3xl">Clear account.</h2></div><CircleDollarSign className="h-6 w-6 text-[#4b743c]" /></div>{outstanding.length ? <div className="mt-6 space-y-3">{outstanding.map(invoice => <div key={invoice.id} className="flex justify-between text-sm"><span>{invoice.invoice_number} · due {formatDate(invoice.due_date)}</span><strong>{formatCurrencyFromCents(invoice.amount_cents)}</strong></div>)}</div> : <p className="mt-6 text-sm text-[#5c705f]">No outstanding invoices.</p>}</div></section></>;
  return <main className="min-h-screen bg-[#f6f1e8] text-[#123c29]"><header className="sticky top-0 z-30 border-b border-[#dfe3da] bg-[#f6f1e8]/90 backdrop-blur-lg"><div className="mx-auto flex h-[74px] max-w-[1440px] items-center justify-between px-5 sm:px-8"><button onClick={() => setLocation("/")} className="flex items-center gap-3"><img src="/manus-storage/north-eastern-mark_65290f75.png" alt="North Eastern Lawn" className="h-10 w-10" /><span className="text-lg font-black">NORTH EASTERN LAWN</span></button><button onClick={signOut} className="icon-button"><LogOut className="h-4 w-4" /></button></div></header><div className="mx-auto grid max-w-[1440px] gap-8 px-5 py-8 sm:px-8 sm:py-11 xl:grid-cols-[180px_minmax(0,1fr)]"><aside><p className="eyebrow mb-4">ACCOUNT MENU</p><nav className="flex gap-2 xl:flex-col"><a href="#overview" className="portal-nav active"><Home className="h-4 w-4" />Overview</a><a href="#schedule" className="portal-nav"><CalendarDays className="h-4 w-4" />Plan</a></nav></aside><div className="space-y-8"><section id="overview" className="relative overflow-hidden rounded-[1.8rem] bg-[#123c29] px-6 py-8 text-white sm:px-10 sm:py-11"><div className="field-grid absolute inset-0 opacity-15" /><div className="relative flex flex-col gap-7 lg:flex-row lg:items-end lg:justify-between"><div><p className="eyebrow text-[#dd784d]">{isFirstTime ? "YOUR FIRST STEP" : "PROPERTY CARE / ACTIVE"}</p><h1 className="display mt-4 text-4xl sm:text-5xl">{isFirstTime ? <>Let’s make a<br /><em>good first cut.</em></> : <>Good to see you, <em>{firstName}.</em></>}</h1><p className="mt-4 max-w-xl leading-7 text-[#cdd9cf]">{isFirstTime ? "No service plan yet — start with a quick quote brief and we’ll take it from there." : "Everything about your service plan, in one clear place."}</p></div><button onClick={() => isFirstTime ? setShowQuoteForm(true) : setShowRequestForm(true)} className="brand-button">{isFirstTime ? "Build my quote" : "Request service"} <ArrowUpRight className="h-4 w-4" /></button></div></section>{notice ? <div className="flex gap-3 rounded-2xl bg-[#dff0b8] px-5 py-4 text-sm font-semibold"><Check className="h-5 w-5" />{notice}</div> : null}{error ? <div className="rounded-2xl bg-[#f4ddd6] p-4 text-sm text-[#8a2d1c]">{error}</div> : null}<section id="schedule">{isFirstTime ? quotePanel : activePanel}</section></div></div>{showQuoteForm ? <QuoteForm busy={busy} close={() => setShowQuoteForm(false)} submit={requestQuote} /> : null}{showPropertyForm ? <PropertyForm busy={busy} close={() => setShowPropertyForm(false)} submit={addProperty} /> : null}{showRequestForm ? <RequestForm busy={busy} close={() => setShowRequestForm(false)} submit={requestService} properties={properties} /> : null}</main>;
}

function QuoteForm({ busy, close, submit }: { busy: boolean; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-scrim"><form onSubmit={submit} className="modal-card"><div className="flex justify-between"><div><p className="eyebrow">YOUR QUOTE BRIEF</p><h2 className="display mt-2 text-3xl">Let’s see the place.</h2></div><button type="button" onClick={close} className="icon-button">×</button></div><div className="mt-7 grid gap-4"><input name="address" required placeholder="Street address" className="portal-input" /><div className="grid grid-cols-2 gap-4"><input name="city" required placeholder="City" className="portal-input" /><input name="state" required placeholder="State" className="portal-input" /></div><input name="postalCode" required placeholder="ZIP code" className="portal-input" /><fieldset><legend className="text-sm font-bold">What should we look at?</legend><div className="mt-3 grid grid-cols-2 gap-2 text-sm">{[["Mowing & maintenance", "Mowing"], ["Seasonal cleanup", "Cleanup"], ["Mulch & beds", "Beds & mulch"], ["Landscape improvement", "Improvements"]].map(([value, label]) => <label key={value} className="flex items-center gap-2 rounded-xl border border-[#c8d3c6] bg-white p-3 font-bold"><input type="checkbox" name="services" value={value} /> {label}</label>)}</div></fieldset><textarea name="notes" rows={3} placeholder="Anything we should know about the property?" className="portal-input resize-none" /></div><button disabled={busy} className="brand-button mt-7 w-full justify-center">{busy ? "Sending…" : "Send quote brief"} <ArrowUpRight className="h-4 w-4" /></button></form></div>; }
function PropertyForm({ busy, close, submit }: { busy: boolean; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-scrim"><form onSubmit={submit} className="modal-card"><div className="flex justify-between"><h2 className="display text-3xl">Add a property</h2><button type="button" onClick={close} className="icon-button">×</button></div><div className="mt-7 grid gap-4"><input name="nickname" required placeholder="Property name" className="portal-input" /><input name="address" required placeholder="Street address" className="portal-input" /><div className="grid grid-cols-2 gap-4"><input name="city" required placeholder="City" className="portal-input" /><input name="state" required placeholder="State" className="portal-input" /></div><input name="postalCode" required placeholder="ZIP code" className="portal-input" /></div><button disabled={busy} className="brand-button mt-7 w-full justify-center">Save property</button></form></div>; }
function RequestForm({ busy, close, submit, properties }: { busy: boolean; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void; properties: Property[] }) { return <div className="modal-scrim"><form onSubmit={submit} className="modal-card"><div className="flex justify-between"><h2 className="display text-3xl">Request service</h2><button type="button" onClick={close} className="icon-button">×</button></div><div className="mt-7 grid gap-4"><select name="propertyId" required className="portal-input"><option value="">Choose a property</option>{properties.map(property => <option key={property.id} value={property.id}>{property.nickname || property.address_line1}</option>)}</select><select name="serviceType" required className="portal-input"><option value="">Choose a service</option><option>Mowing & maintenance</option><option>Seasonal cleanup</option><option>Mulch & beds</option><option>Landscape improvement</option></select><input name="preferredDate" type="date" required className="portal-input" /><textarea name="notes" rows={3} placeholder="Anything the team should know?" className="portal-input resize-none" /></div><button disabled={busy} className="brand-button mt-7 w-full justify-center">Send request</button></form></div>; }
