/** North Eastern Lawn visual system: Cut & Collect. */
import { canCreateQuoteRequest, canCreateServiceRequest, formatCurrencyFromCents } from "@/lib/portalData";
import { Invoice, Property, ServiceVisit, supabase } from "@/lib/supabase";
import { ArrowUpRight, CalendarDays, Check, CircleDollarSign, Loader2, LogOut, MapPin, Sparkles } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { useLocation } from "wouter";

const MARK = "https://files.manuscdn.com/user_upload_by_module/session_file/310519663476184245/nfSjHmOjvvqQCFMt.png";
const PORTAL = "https://files.manuscdn.com/user_upload_by_module/session_file/310519663476184245/lDzupWsPrlUCTEsB.jpg";
type PortalMode = "loading" | "signed-out" | "ready";
const shortName = (email: string) => email.split("@")[0].split(/[._-]/)[0] || "there";

export default function CustomerDashboard() {
  const [, setLocation] = useLocation();
  const [mode, setMode] = useState<PortalMode>("loading");
  const [name, setName] = useState("there"); const [properties, setProperties] = useState<Property[]>([]); const [visits, setVisits] = useState<ServiceVisit[]>([]); const [invoices, setInvoices] = useState<Invoice[]>([]); const [quoteStatus, setQuoteStatus] = useState<string | null>(null); const [showQuote, setShowQuote] = useState(false); const [showRequest, setShowRequest] = useState(false); const [notice, setNotice] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const isNew = !properties.length && !visits.length && !invoices.length;
  const openInvoice = useMemo(() => invoices.find(invoice => ["open", "overdue"].includes(invoice.status)) ?? null, [invoices]);
  async function load() { const { data } = await supabase.auth.getSession(); const user = data.session?.user; if (!user) { setMode("signed-out"); return; } setName((user.user_metadata.full_name || shortName(user.email || "there")).split(" ")[0]); await supabase.from("profiles").upsert({ id: user.id, full_name: user.user_metadata.full_name || null }, { onConflict: "id" }); const [p, v, i, q] = await Promise.all([supabase.from("properties").select("id,nickname,address_line1,city,state,postal_code").order("created_at"), supabase.from("service_visits").select("id,scheduled_start,service_type,status,notes_for_customer").order("scheduled_start").limit(8), supabase.from("invoices").select("id,invoice_number,amount_cents,due_date,status").order("due_date").limit(8), supabase.from("quote_requests").select("status").order("created_at", { ascending: false }).limit(1)]); setProperties((p.data ?? []) as Property[]); setVisits((v.data ?? []) as ServiceVisit[]); setInvoices((i.data ?? []) as Invoice[]); setQuoteStatus(q.data?.[0]?.status ?? null); setError(p.error?.message || v.error?.message || i.error?.message || q.error?.message || ""); setMode("ready"); }
  useEffect(() => { void load(); const { data } = supabase.auth.onAuthStateChange(() => void load()); return () => data.subscription.unsubscribe(); }, []);
  async function signOut() { await supabase.auth.signOut(); setLocation("/"); }
  async function submitQuote(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const userId = (await supabase.auth.getSession()).data.session?.user.id; const input = { address: String(form.get("address") || ""), city: String(form.get("city") || ""), state: String(form.get("state") || ""), postalCode: String(form.get("postalCode") || ""), serviceInterests: form.getAll("services").map(String) }; if (!userId || !canCreateQuoteRequest(input)) { setBusy(false); return setError("Add the address and choose at least one service."); } const { error: insertError } = await supabase.from("quote_requests").insert({ profile_id: userId, property_address: input.address, city: input.city, state: input.state, postal_code: input.postalCode, service_interests: input.serviceInterests, property_notes: String(form.get("notes") || "") || null }); setBusy(false); if (insertError) return setError(insertError.message); setShowQuote(false); setQuoteStatus("submitted"); setNotice("Quote brief received. We’ll be in touch with the next step."); }
  async function submitRequest(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); const userId = (await supabase.auth.getSession()).data.session?.user.id; const input = { propertyId: String(form.get("propertyId") || ""), serviceType: String(form.get("serviceType") || ""), preferredDate: String(form.get("preferredDate") || "") }; if (!userId || !canCreateServiceRequest(input)) { setBusy(false); return setError("Choose a property, service, and preferred date."); } const { error: insertError } = await supabase.from("service_requests").insert({ profile_id: userId, property_id: input.propertyId, service_type: input.serviceType, preferred_date: input.preferredDate, notes: String(form.get("notes") || "") || null }); setBusy(false); if (insertError) return setError(insertError.message); setShowRequest(false); setNotice("Request received. We’ll confirm the next step."); }
  if (mode === "loading") return <div className="grid min-h-screen place-items-center bg-[#f6f1e8]"><Loader2 className="h-8 w-8 animate-spin text-[#123c29]" /></div>;
  if (mode === "signed-out") return <main className="min-h-screen bg-[#123c29] p-4 text-white"><section className="relative mx-auto flex min-h-[calc(100vh-2rem)] max-w-lg items-end overflow-hidden rounded-[1.6rem] p-7"><img src={PORTAL} alt="North Eastern Lawn property" className="absolute inset-0 h-full w-full object-cover opacity-45" /><div className="absolute inset-0 bg-gradient-to-b from-[#123c29]/25 via-[#123c29]/75 to-[#123c29]" /><div className="relative"><img src={MARK} alt="North Eastern Lawn" className="h-11 w-11 rounded-full bg-[#f6f1e8]" /><p className="eyebrow mt-12 text-[#dd784d]">CUSTOMER PORTAL / START HERE</p><h1 className="display mt-4 text-5xl leading-[.86]">Your quote<br /><em>starts outside.</em></h1><p className="mt-5 max-w-sm leading-7 text-[#d3dfd2]">Sign in, share the place, and we’ll bring back a plan.</p><button onClick={() => setLocation("/login")} className="mt-8 inline-flex h-13 items-center gap-2 rounded-full bg-[#dd784d] px-5 text-sm font-black text-[#123c29]">Continue to sign-in <ArrowUpRight className="h-4 w-4" /></button></div></section></main>;
  return <main className="min-h-screen bg-[#f6f1e8] pb-8 text-[#123c29]"><header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-[#e0e5dc] bg-[#f6f1e8]/95 px-5 backdrop-blur"><button onClick={() => setLocation("/")} className="flex items-center gap-2"><img src={MARK} alt="North Eastern Lawn" className="h-9 w-9" /><span className="text-xs font-black tracking-[.08em]">NORTH EASTERN<br />LAWN</span></button><button onClick={signOut} className="grid h-10 w-10 place-items-center rounded-full border border-[#bdcabb]"><LogOut className="h-4 w-4" /></button></header><div className="mx-auto max-w-lg space-y-4 px-4 pt-5"><section className="relative overflow-hidden rounded-[1.6rem] bg-[#123c29] p-6 text-white"><div className="field-grid absolute inset-0 opacity-15" /><div className="relative"><p className="eyebrow text-[#dd784d]">{isNew ? "YOUR FIRST STEP" : "PROPERTY CARE"}</p><h1 className="display mt-3 text-4xl leading-[.88]">{isNew ? <>Let’s make a<br /><em>good first cut.</em></> : <>Hey, <em>{name}.</em></>}</h1><p className="mt-4 max-w-sm text-sm leading-6 text-[#d3dfd2]">{isNew ? "Start with a quick quote brief. We’ll shape the plan around your property." : "Your property care, at a glance."}</p>{isNew && !quoteStatus ? <button onClick={() => setShowQuote(true)} className="mt-6 inline-flex h-12 items-center gap-2 rounded-full bg-[#dd784d] px-5 text-sm font-black text-[#123c29]">Build my quote <ArrowUpRight className="h-4 w-4" /></button> : null}</div></section>{notice ? <div className="flex gap-2 rounded-xl bg-[#dff0b8] p-4 text-sm font-bold"><Check className="h-5 w-5" />{notice}</div> : null}{error ? <div className="rounded-xl bg-[#f4ddd6] p-4 text-sm text-[#8a2d1c]">{error}</div> : null}{isNew ? <NewCustomerCard quoteStatus={quoteStatus} openQuote={() => setShowQuote(true)} /> : <ActiveCustomerCard properties={properties} visits={visits} invoice={openInvoice} openRequest={() => setShowRequest(true)} />}</div>{showQuote ? <QuoteForm busy={busy} close={() => setShowQuote(false)} submit={submitQuote} /> : null}{showRequest ? <RequestForm busy={busy} close={() => setShowRequest(false)} submit={submitRequest} properties={properties} /> : null}</main>;
}
function NewCustomerCard({ quoteStatus, openQuote }: { quoteStatus: string | null; openQuote: () => void }) { return <section className="overflow-hidden rounded-[1.6rem] bg-white shadow-[0_10px_30px_rgba(20,60,42,.09)]"><img src={PORTAL} alt="Home ready for property care" className="h-48 w-full object-cover" /><div className="p-6"><div className="flex items-center gap-2"><Sparkles className="h-5 w-5 text-[#dd784d]" /><p className="eyebrow">{quoteStatus ? "QUOTE BRIEF RECEIVED" : "YOUR 3-STEP PLAN"}</p></div><h2 className="display mt-4 text-3xl">{quoteStatus ? <>We’re on<br /><em>your place.</em></> : <>Your place.<br /><em>Your quote.</em></>}</h2><p className="mt-3 text-sm leading-6 text-[#5c705f]">{quoteStatus ? "Your brief is with the team. We’ll be back with the next step." : "1. Share the address. 2. Pick the work. 3. Get a clear plan."}</p>{quoteStatus ? <span className="mt-5 inline-flex items-center gap-2 rounded-full bg-[#dff0b8] px-4 py-2 text-sm font-bold"><Check className="h-4 w-4" />Submitted</span> : <button onClick={openQuote} className="mt-5 inline-flex h-12 items-center gap-2 rounded-full bg-[#123c29] px-5 text-sm font-black text-white">Start my quote <ArrowUpRight className="h-4 w-4" /></button>}</div></section>; }
function ActiveCustomerCard({ properties, visits, invoice, openRequest }: { properties: Property[]; visits: ServiceVisit[]; invoice: Invoice | null; openRequest: () => void }) { const visit = visits[0]; return <section className="space-y-4"><div className="rounded-[1.6rem] bg-white p-6 shadow-[0_10px_30px_rgba(20,60,42,.09)]"><div className="flex items-center justify-between"><div><p className="eyebrow">UP NEXT</p><h2 className="display mt-2 text-3xl">{visit?.service_type || "Nothing scheduled"}</h2></div><CalendarDays className="h-6 w-6 text-[#4b743c]" /></div><p className="mt-4 text-sm leading-6 text-[#5c705f]">{visit?.notes_for_customer || "Request a service when your property needs attention."}</p><button onClick={openRequest} className="mt-5 inline-flex h-11 items-center gap-2 rounded-full bg-[#dd784d] px-4 text-sm font-black text-[#123c29]">Request service <ArrowUpRight className="h-4 w-4" /></button></div><div className="grid grid-cols-2 gap-4"><div className="rounded-2xl bg-[#e5eee2] p-4"><MapPin className="h-5 w-5 text-[#4b743c]" /><p className="mt-6 text-sm font-bold">{properties.length} {properties.length === 1 ? "property" : "properties"}</p></div><div className="rounded-2xl bg-[#f4c765] p-4"><CircleDollarSign className="h-5 w-5" /><p className="mt-6 text-sm font-bold">{invoice ? formatCurrencyFromCents(invoice.amount_cents) : "All clear"}</p></div></div></section>; }
function QuoteForm({ busy, close, submit }: { busy: boolean; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void }) { return <div className="modal-scrim items-end sm:items-center"><form onSubmit={submit} className="modal-card max-h-[92vh] overflow-y-auto"><div className="flex justify-between"><div><p className="eyebrow">QUOTE BRIEF</p><h2 className="display mt-2 text-3xl">Tell us the place.</h2></div><button type="button" onClick={close} className="icon-button">×</button></div><div className="mt-6 grid gap-3"><input name="address" required placeholder="Street address" className="portal-input" /><div className="grid grid-cols-2 gap-3"><input name="city" required placeholder="City" className="portal-input" /><input name="state" required placeholder="State" className="portal-input" /></div><input name="postalCode" required placeholder="ZIP code" className="portal-input" /><div className="grid grid-cols-2 gap-2 text-sm">{[["Mowing & maintenance", "Mowing"], ["Seasonal cleanup", "Cleanup"], ["Mulch & beds", "Beds & mulch"], ["Landscape improvement", "Improvements"]].map(([value, label]) => <label key={value} className="flex items-center gap-2 rounded-xl border border-[#c8d3c6] bg-white p-3 font-bold"><input type="checkbox" name="services" value={value} />{label}</label>)}</div><textarea name="notes" rows={3} placeholder="Anything we should know?" className="portal-input resize-none" /></div><button disabled={busy} className="brand-button mt-6 w-full justify-center">{busy ? "Sending…" : "Send quote brief"}<ArrowUpRight className="h-4 w-4" /></button></form></div>; }
function RequestForm({ busy, close, submit, properties }: { busy: boolean; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void; properties: Property[] }) { return <div className="modal-scrim items-end sm:items-center"><form onSubmit={submit} className="modal-card"><div className="flex justify-between"><h2 className="display text-3xl">Request service</h2><button type="button" onClick={close} className="icon-button">×</button></div><div className="mt-6 grid gap-3"><select name="propertyId" required className="portal-input"><option value="">Choose a property</option>{properties.map(property => <option key={property.id} value={property.id}>{property.nickname || property.address_line1}</option>)}</select><select name="serviceType" required className="portal-input"><option value="">Choose a service</option><option>Mowing & maintenance</option><option>Seasonal cleanup</option><option>Mulch & beds</option><option>Landscape improvement</option></select><input name="preferredDate" type="date" required className="portal-input" /><textarea name="notes" rows={3} placeholder="Anything the team should know?" className="portal-input resize-none" /></div><button disabled={busy} className="brand-button mt-6 w-full justify-center">Send request</button></form></div>; }
